// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdMWcQODE9G-MPug_M7CH3JTakoYTcsk',
    appId: '1:820149808039:web:9ca438599430df5bce2482',
    messagingSenderId: '820149808039',
    projectId: 'doancuoiki-10573',
    authDomain: 'doancuoiki-10573.firebaseapp.com',
    storageBucket: 'doancuoiki-10573.firebasestorage.app',
    measurementId: 'G-BRBBD5CYT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHam8-4QK4z0yw-FpW1mawLPImHbJxRs',
    appId: '1:820149808039:android:8295fc710ea7538dce2482',
    messagingSenderId: '820149808039',
    projectId: 'doancuoiki-10573',
    storageBucket: 'doancuoiki-10573.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfCExO1xr3zKGn01aBbRCkMcPIUZGaMwQ',
    appId: '1:820149808039:ios:fb36e1139249659dce2482',
    messagingSenderId: '820149808039',
    projectId: 'doancuoiki-10573',
    storageBucket: 'doancuoiki-10573.firebasestorage.app',
    iosBundleId: 'com.example.doanCuoiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfCExO1xr3zKGn01aBbRCkMcPIUZGaMwQ',
    appId: '1:820149808039:ios:fb36e1139249659dce2482',
    messagingSenderId: '820149808039',
    projectId: 'doancuoiki-10573',
    storageBucket: 'doancuoiki-10573.firebasestorage.app',
    iosBundleId: 'com.example.doanCuoiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmdMWcQODE9G-MPug_M7CH3JTakoYTcsk',
    appId: '1:820149808039:web:8254b588e56ba033ce2482',
    messagingSenderId: '820149808039',
    projectId: 'doancuoiki-10573',
    authDomain: 'doancuoiki-10573.firebaseapp.com',
    storageBucket: 'doancuoiki-10573.firebasestorage.app',
    measurementId: 'G-ZFZFYF293V',
  );
}
